defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: JinWoo Kim
subtitle: Full-Stack Developer

left_side:
  background_image: "./assets/images/sponge.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"

footer:
  copyright_text: "&copy; Christian Ezeani"

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: About Me
    link: /resume
    icon: ""

  - text: Skills & Offers
    link: /skills-and-offers
    icon: ""

  - text: Projects
    link: /blog
    icon: ""

  - text: Contact Me
    link: /contact
    icon: ""


# Socialmedia Icons
social_icons:
  - name: mail
    link: mailto://tmvhswlqkqn_@naver.com
    icon: fab fa-mail

  - name: github
    link: https://github.com/tigre911
    icon: fab fa-github-square

  - name: tistory
    link: https://tigre911.tistory.com/
    icon: fab fa-blogger-b

  - name: instargram
    link: https://www.instagram.com/vvowls
    icon: fab fa-instagram

